version: "3.8"

services:
  ansible:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy=http://10.226.44.26:3128
        - https_proxy=http://10.226.44.26:3128
    container_name: ansible
    tty: true
    stdin_open: true
    restart: always
    environment:
      - http_proxy=http://10.226.44.26:3128
      - https_proxy=http://10.226.44.26:3128
      - no_proxy=127.0.0.1,localhost
    volumes:
      - /home/ansible/.ssh:/root/.ssh        # Mount SSH keys
      - /home/ansible:/ansible   # mount your entire ansible home
      - /home/dock-file:/home/dock-file 
    working_dir: /ansible        # drop directly into your files
