version: '3.9'

services:
  ansible:
    build: .
    container_name: ansible-controller
    working_dir: /ansible
    volumes:
      # Mount your local playbooks and inventory
      - ./playbooks:/ansible/playbooks
      - ./inventory:/ansible/inventory
      # Mount SSH keys (read-only)
      - ~/.ssh:/root/.ssh:ro
      # Optional: mount ansible.cfg
      - ./ansible.cfg:/ansible/ansible.cfg:ro
    stdin_open: true
    tty: true
    # Run a test command by default
    command: >
      sh -c "
      python3 --version &&
      ansible --version &&
      echo '✅ Ansible environment is ready.'
      "